export const SITEMAP_URLS = [
  { url: 'https://bymamstudio.com/', priority: '1.0' },
  { url: 'https://bymamstudio.com/products', priority: '0.9' },
  { url: 'https://bymamstudio.com/products/ai-marketing-engine', priority: '0.8' },
  { url: 'https://bymamstudio.com/products/ai-readiness-scorecard', priority: '0.8' },
  { url: 'https://bymamstudio.com/products/ai-hr-playbook', priority: '0.8' },
  { url: 'https://bymamstudio.com/products/claude-skills-playbook', priority: '0.8' },
  { url: 'https://bymamstudio.com/services', priority: '0.9' },
  { url: 'https://bymamstudio.com/services/ai-audit', priority: '0.8' },
  { url: 'https://bymamstudio.com/services/marketing-ai-sprint', priority: '0.8' },
  { url: 'https://bymamstudio.com/services/hr-ai-sprint', priority: '0.8' },
  { url: 'https://bymamstudio.com/services/skills-library-build', priority: '0.8' },
  { url: 'https://bymamstudio.com/services/ai-retainer', priority: '0.8' },
  { url: 'https://bymamstudio.com/about', priority: '0.8' },
  { url: 'https://bymamstudio.com/contact', priority: '0.8' },
  { url: 'https://bymamstudio.com/resources', priority: '0.8' },
  { url: 'https://bymamstudio.com/resources/ai-implementation-guide-small-business', priority: '0.7' },
  { url: 'https://bymamstudio.com/resources/what-is-ai-readiness-assessment', priority: '0.7' },
  { url: 'https://bymamstudio.com/resources/ai-governance-framework-small-business', priority: '0.7' },
  { url: 'https://bymamstudio.com/resources/claude-skills-library-guide', priority: '0.7' },
  { url: 'https://bymamstudio.com/resources/ai-marketing-automation-guide', priority: '0.7' },
  { url: 'https://bymamstudio.com/resources/hr-ai-implementation-guide', priority: '0.7' },
  { url: 'https://bymamstudio.com/resources/ai-consulting-new-york', priority: '0.7' },
  { url: 'https://bymamstudio.com/resources/ai-maturity-tiers-explained', priority: '0.7' },
  { url: 'https://bymamstudio.com/assessment', priority: '0.8' },
]
